Completing Global Search
CBIIT/bento-gmb-frontend pull request #33
Opened 2022-04-27 05:56 UTC by ogwuazors

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

2022-04-27 16:20 UTC, iksheth requested changes

2022-04-27 16:20 UTC, iksheth commented on src/pages/search/components/cards/siteCard.js
> +//   const properties = [
@ogwuazors Can we remove commented section if not needed in future ?

2022-04-27 16:20 UTC, iksheth commented on src/pages/fileCentricCart/cartController.js
> +export default cartController; */
@ogwuazors Why we are not exporting cartController this way?

2022-04-27 16:58 UTC, ogwuazors commented on src/pages/search/components/cards/siteCard.js
> +//   const properties = [
It's been removed

2022-05-03 19:11 UTC, iksheth commented
Closing this one as code base is re-written from Bento 3.7.0

2022-05-03 19:11 UTC, closed without merging